[package]
name = "gear-program"
version = "0.1.1"
authors = ["clearloop <clearloop@users.noreply.github.com>"]
edition = "2021"
description = "gear program cli"
repository = "https://github.com/clearloop/gear-program"
license = "GPL-3.0"
documentation = "https://docs.rs/gear-program"
homepage = "https://github.com/clearloop/gear-program"
keywords = ["gear", "cli", "wasm"]
readme = './README.md'

[[bin]]
path = "bin/gear.rs"
name = "gear"

[[bin]]
path = "bin/generate-api.rs"
name = "generate-api"
required-features = [ "builder" ]

[dependencies]
dialoguer = "0.10.1"
dirs = "4.0.0"
env_logger = "0.9.0"
futures-util = "0.3.21"
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.16"
parity-scale-codec = "3.1.2"
structopt = "0.3.26"
subxt = "0.21.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = [ "full" ] }

[features]
builder = []
