name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown

      - name: Run Tests
        run: |
          ./scripts/download-gear.sh res
          cargo test --all --all-features

  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown


      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: Swatinem/rust-cache@v2

      - name: "Check formatting: repo"
        run: cargo +nightly fmt --all --check

      - name: "Check clippy: repo"
        run: SKIP_WASM_BUILD=1 cargo clippy --workspace --all-targets --all-features -- --no-deps -D warnings
